#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Android本地化翻译脚本 - 只翻译缺失的key
规则：只要目标文件中已存在key，就跳过不翻译
"""

import os
import sys
import time
import re
from lxml import etree
from tqdm import tqdm
import requests

# 导入配置
try:
    from config import *
except ImportError:
    print("❌ 找不到 config.py 配置文件")
    sys.exit(1)

# =====================================================
# 路径计算函数
# =====================================================
def setup_paths():
    """自动计算项目路径"""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(script_dir, "../.."))
    source_file = os.path.join(project_root, SOURCE_RELATIVE_PATH)
    res_dir = os.path.dirname(os.path.dirname(source_file))

    return project_root, res_dir, source_file

# =====================================================
# XML处理函数
# =====================================================
def load_strings(file_path):
    """
    加载strings.xml文件
    返回：{key: value} 字典
    """
    if not os.path.exists(file_path):
        return {}

    try:
        parser = etree.XMLParser(remove_blank_text=True)
        tree = etree.parse(file_path, parser)
        root = tree.getroot()

        strings = {}
        for node in root.findall("string"):
            # 只检查translatable不为false的
            if node.get("translatable") != "false":
                name = node.get("name")
                text = node.text or ""
                strings[name] = text

        return strings
    except Exception as e:
        print(f"❌ 解析XML失败 {file_path}: {e}")
        return {}

def save_strings(file_path, strings):
    """保存strings.xml文件"""
    try:
        root = etree.Element("resources")

        # 添加生成注释
        comment = etree.Comment(f" Generated by translation script on {time.strftime('%Y-%m-%d %H:%M:%S')} ")
        root.append(comment)

        for name, text in sorted(strings.items()):
            elem = etree.SubElement(root, "string", name=name)
            if text:
                # 转义单引号
                text = text.replace("'", "\\'")
                elem.text = text

        # 创建目录
        os.makedirs(os.path.dirname(file_path), exist_ok=True)

        # 保存文件
        tree = etree.ElementTree(root)
        tree.write(file_path, encoding="utf-8", xml_declaration=True, pretty_print=True)

        return True
    except Exception as e:
        print(f"❌ 保存文件失败 {file_path}: {e}")
        return False

# =====================================================
# 简单直接的翻译逻辑
# =====================================================
def find_missing_keys(source_strings, existing_strings):
    """
    找出缺失的key（只找不存在于existing_strings中的key）
    规则：只要key存在，就跳过，不管内容是什么
    """
    missing_keys = {}

    for key, value in source_strings.items():
        if key not in existing_strings:
            missing_keys[key] = value

    return missing_keys

def translate_text(text, target_lang):
    """调用DeepSeek API翻译文本"""
    if not text or not text.strip():
        return ""

    # 简洁的提示词
    prompt = f"将以下Android应用文本翻译成{target_lang}，保持占位符(%s,%d)和HTML标签不变，只返回翻译结果：\n{text}"

    headers = {
        "Authorization": f"Bearer {DEEPSEEK_API_KEY}",
        "Content-Type": "application/json"
    }

    data = {
        "model": MODEL,
        "messages": [
            {"role": "system", "content": "Android应用本地化翻译助手"},
            {"role": "user", "content": prompt}
        ],
        "temperature": 0.3,
        "max_tokens": 300
    }

    try:
        response = requests.post(API_URL, headers=headers, json=data, timeout=30)
        response.raise_for_status()

        result = response.json()
        if result.get("choices"):
            translated = result["choices"][0]["message"]["content"].strip()
            return translated

        return text  # 失败时返回原文

    except Exception as e:
        print(f"⚠️ 翻译失败: {e}")
        return None

# =====================================================
# 主函数
# =====================================================
def main():
    print("🚀 Android本地化翻译开始")
    print("📌 规则：只翻译缺失的key，已有key（无论内容）一律跳过")
    print("=" * 60)

    # 检查API密钥
    if not DEEPSEEK_API_KEY or DEEPSEEK_API_KEY.startswith("sk-你的"):
        print("❌ 请在 config.py 中设置正确的 DeepSeek API Key")
        return

    # 计算路径
    project_root, res_dir, source_file = setup_paths()
    print(f"📁 项目根目录: {project_root}")
    print(f"📁 资源目录: {res_dir}")

    # 检查源文件是否存在
    if not os.path.exists(source_file):
        print(f"❌ 找不到源文件: {source_file}")
        return

    # 加载源字符串
    source_strings = load_strings(source_file)
    if not source_strings:
        print("❌ 源文件中没有可翻译的字符串")
        return

    print(f"📄 源文件: {os.path.basename(source_file)}")
    print(f"📝 源字符串数量: {len(source_strings)}")
    print(f"🌐 目标语言: {len(TARGET_LANGS)} 种")

    total_missing = 0
    total_existing = 0
    total_translated = 0

    # 处理每种语言
    for lang_name, folder in TARGET_LANGS.items():
        print(f"\n{'='*50}")
        print(f"🌍 处理: {lang_name} ({folder})")

        # 目标文件路径
        target_file = os.path.join(res_dir, folder, "strings.xml")
        print(f"📁 目标文件: {target_file}")

        # 加载现有翻译
        existing_strings = load_strings(target_file)

        # 统计现有key数量
        existing_count = len(existing_strings)
        total_existing += existing_count

        if existing_count > 0:
            print(f"📊 已有 {existing_count} 个翻译（全部保留）")

        # 找出缺失的key（只找不存在的key）
        missing_keys = find_missing_keys(source_strings, existing_strings)
        missing_count = len(missing_keys)
        total_missing += missing_count

        if not missing_keys:
            print("✅ 没有缺失的key，跳过翻译")
            continue

        print(f"🔍 发现 {missing_count} 个缺失的key需要翻译")

        # 显示部分缺失的key
        print("📝 缺失key示例（前3个）:")
        for i, (key, value) in enumerate(list(missing_keys.items())[:3]):
            display_value = value[:50] + "..." if len(value) > 50 else value
            print(f"  {key}: '{display_value}'")

        # 翻译缺失的key
        success = 0
        failed = 0

        for key, value in tqdm(missing_keys.items(), desc=f"翻译缺失key"):
            translated = translate_text(value, lang_name)

            if translated:
                existing_strings[key] = translated  # 添加到现有翻译中
                success += 1
                total_translated += 1
                time.sleep(REQUEST_DELAY)
            else:
                # 翻译失败，保留原文
                existing_strings[key] = value
                failed += 1
                time.sleep(REQUEST_DELAY * 2)

        # 保存合并后的翻译文件
        if save_strings(target_file, existing_strings):
            print(f"💾 已保存: {folder}/strings.xml")
            print(f"✅ 新增翻译: {success}个")
            if failed > 0:
                print(f"⚠️  翻译失败: {failed}个")
        else:
            print(f"❌ 保存失败: {target_file}")

    # 总结
    print(f"\n{'='*60}")
    print("🎉 翻译完成!")
    print(f"📊 统计汇总:")
    print(f"   源字符串总数: {len(source_strings)}")
    print(f"   已有翻译key数: {total_existing}（全部保留）")
    print(f"   缺失key数: {total_missing}")
    print(f"   本次新增翻译: {total_translated}")
    print(f"   跳过翻译: {total_existing}（尊重现有翻译）")
    print("=" * 60)

# 可选：查看详细对比
def show_key_comparison():
    """显示源文件和目标文件的key对比"""
    print("\n🔍 Key对比分析")
    print("=" * 60)

    project_root, res_dir, source_file = setup_paths()
    source_strings = load_strings(source_file)

    print(f"源文件key总数: {len(source_strings)}")

    for lang_name, folder in TARGET_LANGS.items():
        target_file = os.path.join(res_dir, folder, "strings.xml")
        existing_strings = load_strings(target_file)

        # 找出交集和差集
        source_keys = set(source_strings.keys())
        existing_keys = set(existing_strings.keys())

        common_keys = source_keys & existing_keys  # 都有的key
        missing_keys = source_keys - existing_keys  # 源有目标无
        extra_keys = existing_keys - source_keys    # 目标有源无（多余的）

        print(f"\n{lang_name} ({folder}):")
        print(f"  已有key: {len(existing_keys)}个")
        print(f"  共同key: {len(common_keys)}个（跳过不翻译）")
        print(f"  缺失key: {len(missing_keys)}个（需要翻译）")

        if extra_keys:
            print(f"  多余key: {len(extra_keys)}个（目标文件中有但源文件中没有）")
            for key in list(extra_keys)[:3]:
                print(f"    - {key}")

if __name__ == "__main__":
    # 如果需要查看key对比，取消下面一行的注释
    # show_key_comparison()

    main()